### ISSUE TITLE
redirectの後に続く無関係のargvが取れていない

### ISSUE THREAD

**Issue by naopen** [naopen/42-minishell#20]
1つのプロセスは1個のnodeで作る

minishell> echo a > out ksdnsd
みたいなときBashは後ろも入ってる

**Comment by masakikaihori** [comment]
void	print_node(t_node *node)
{
	int			i;
	t_redirect	*temp;

	i = 0;
	printf("=====node debug=====\n");
	while (node)
	{
		printf("node type : %d\n", node->type);
		while (node->argv[i])
		{
			printf("node argv %d: %s\n", i + 1, node->argv[i]);
			i++;
		}
		i = 0;
		temp = node->redirects;
		while (temp)
		{
			printf("redirects type : %d\n", temp->type);
			printf("redirects filename : %s\n", temp->file_name);
			temp = temp->next;
		}
		node = node->next;
		printf("\n");
	}
	printf("=====node debug=====\n");
	return ;
}
